export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? "";
export const PUBLIC_SITE_URL = (import.meta.env.VITE_PUBLIC_SITE_URL ?? window.location.origin).replace(/\/+$/, "");
export const DEPLOY_TARGET = import.meta.env.VITE_DEPLOY_TARGET ?? "app";
export const IS_LANDING = DEPLOY_TARGET === "landing";
export const APP_BASE_URL = (import.meta.env.VITE_APP_BASE_URL || PUBLIC_SITE_URL).replace(/\/+$/, "");
export const YEAR = new Date().getFullYear();
export const SESSION_STORAGE_KEY = "inclusive-hire-session";
export const VISITOR_STORAGE_KEY = "inclusive-hire-visitor";

export const publicSeo = {
  title: "Найм людей с инвалидностью в Бишкеке | inclusive-hire",
  description: "inclusive-hire Бишкек — некоммерческая платформа инклюзивного найма в Кыргызстане: работодатели могут нанять человека с инвалидностью, соискатели загружают резюме и показывают навыки.",
  robots: IS_LANDING ? "index,follow,max-image-preview:large" : "noindex,nofollow",
  canonicalPath: "/"
};

export const statusLabels = {
  Viewed: "Просмотрен",
  Contacted: "Связались",
  Hired: "Нанят"
};

export const statuses = Object.keys(statusLabels);

export const availabilityOptions = [
  "Готов(а) к предложениям",
  "Открыт(а) к проектной работе",
  "Рассматриваю предложения",
  "Не ищу работу сейчас"
];

export const employmentFormatLabels = {
  remote: "Онлайн",
  office: "Офлайн",
  hybrid: "Гибрид"
};

export const roleLabels = {
  candidate: "Соискатель",
  hiring_manager: "Работодатель",
  admin: "Админ"
};

export const emptyAuthForm = { name: "", email: "", password: "", role: "candidate" };
export const emptyResetForm = { email: "", token: "", password: "" };
export const emptyAccountForm = { name: "" };
export const emptyProfileForm = {
  headline: "",
  specialization: "",
  summary: "",
  skills: "",
  languages: "",
  accessibilityPreferences: "",
  location: "",
  portfolio: "",
  availability: "Готов(а) к предложениям",
  employmentFormat: "remote",
  contactEmail: "",
  messengerType: "telegram",
  messenger: ""
};
export const emptyRecruiterForm = {
  name: "",
  description: "",
  website: "",
  contactEmail: "",
  phone: "",
  messenger: "",
  accessibilityCommitments: ""
};
export const emptyFilters = { query: "", specialization: "", location: "", employmentFormat: "", skills: "", languages: "" };

export const specializationOptions = [
  "Инженерия",
  "Бэкенд",
  "Фронтенд",
  "Фулстек",
  "Веб Разработка",
  "ERP Разработка (1С, SAP)",
  "Embedded & IoT",
  "Мобильная Разработка",
  "Data Science & ML",
  "Архитектура",
  "Engineering Менеджмент",
  "Product Менеджмент",
  "Project Менеджмент",
  "Program Менеджмент",
  "Деливери Менеджмент",
  "Управление",
  "Аналитика Данных",
  "Наука И R&D",
  "Бизнес-Аналитика",
  "Системная Аналитика",
  "Разработка ИИ",
  "AI-Тренинг",
  "DevOps",
  "Системная Инженерия",
  "Кибербезопасность",
  "Тестирование",
  "UI/UX Дизайн",
  "Продуктовый Дизайн",
  "Графический Дизайн",
  "Motion Дизайн",
  "Видеопроизводство",
  "Разработка Игр",
  "Гейм-Дизайн",
  "Игровая Графика",
  "Level-Дизайн",
  "Продюсер Игр",
  "Маркетинг & Creative",
  "PR И Коммуникации",
  "Создание Контента",
  "Продажи & Биздев",
  "Поддержка Клиентов",
  "Консалтинг",
  "Рекрутинг",
  "HR",
  "HRBP/HRD/PP",
  "Финансы",
  "Юриспруденция",
  "Администрирование",
  "Логистика И Закупки",
  "Образование",
  "Медицина",
  "Другое"
];

export const skillOptions = [
  "ai",
  "python",
  "sql",
  "project management",
  "saas",
  "aws",
  "kubernetes",
  "ci cd",
  "docker",
  "startup",
  "crm",
  "sales",
  "fintech",
  "java",
  "agile",
  "data analysis",
  "typescript",
  "postgresql",
  "excel",
  "javascript",
  "git",
  "linux",
  "react",
  "stakeholder management",
  "salesforce",
  "russian",
  "jira",
  "account management",
  "english",
  "api",
  "communication",
  "azure",
  "go",
  "business development",
  "figma",
  "cloud",
  "product management",
  "machine learning",
  "microservices",
  "gcp",
  "llm",
  "leadership",
  "b2b",
  "risk management",
  "automation",
  "analytics",
  "terraform",
  "rest api",
  "cybersecurity",
  "kafka",
  "node",
  "devops",
  "c++",
  "compliance",
  "negotiation",
  "customer service",
  "qa",
  "distributed systems",
  "freelance",
  "marketing",
  "scrum",
  "team leadership",
  "power bi",
  "team management",
  "microsoft office",
  "ecommerce",
  "igaming",
  "ux",
  "mysql",
  "networking",
  "erp",
  "customer success",
  "confluence",
  "a b testing",
  "c#",
  "redis",
  "tableau",
  "social media",
  "sap",
  "content creation",
  "rest",
  "b2b sales",
  "qa automation",
  "backend",
  "problem solving",
  "troubleshooting",
  "seo",
  "html",
  "manufacturing",
  "ui",
  "bash",
  "healthcare",
  ".net",
  "security",
  "lead generation",
  "enterprise sales",
  "grafana",
  "startup experience",
  "customer support",
  "css",
  "php",
  "digital marketing",
  "kotlin",
  "mongodb",
  "ml",
  "budgeting",
  "etl",
  "crypto",
  "finance",
  "smm",
  "jenkins",
  "business analysis",
  "supply chain",
  "accounting",
  "forecasting",
  "product strategy",
  "vue",
  "ansible",
  "rabbitmq",
  "web3",
  "reporting",
  "strategy",
  "change management",
  "hr",
  "program management",
  "photoshop",
  "mentoring",
  "android",
  "data analytics",
  "pytorch",
  "windows",
  "angular",
  "vendor management",
  "payments",
  "fastapi",
  "logistics",
  "prometheus",
  "ios",
  "graphql",
  "gamedev",
  "german",
  "blockchain",
  "rag",
  "copywriting",
  "oracle",
  "performance marketing",
  "prototyping",
  "postman",
  "financial modeling",
  "gitlab",
  "next",
  "regulatory compliance",
  "market research",
  "strategic planning",
  "budget management",
  "data science",
  "kpi",
  "technical support",
  "recruiting",
  "onboarding",
  "kanban",
  "hubspot",
  "generative ai",
  "financial services",
  "data visualization",
  "telegram",
  "process improvement",
  "testing",
  "nosql",
  "data engineering",
  "operations",
  "financial analysis",
  "spark",
  "financial reporting",
  "github",
  "spring boot",
  "procurement",
  "playwright",
  "data modeling",
  "spanish",
  "communication skills",
  "ms office",
  "airflow",
  "observability",
  "pipeline management",
  "1c",
  "google sheets",
  "robotics",
  "infrastructure",
  "powershell",
  "nlp",
  "data pipelines",
  "talent acquisition",
  "video editing",
  "people management",
  "software development",
  "unity",
  "banking",
  "mlops",
  "cross functional collaboration"
];

export const sampleCandidates = [
  {
    name: "Айжан М.",
    headline: "UX-исследователь доступных сервисов",
    specialization: "UI/UX Дизайн",
    location: "Бишкек",
    skills: ["исследования", "интервью", "аналитика"],
    languages: ["кыргызча", "русский", "English"]
  },
  {
    name: "Тимур К.",
    headline: "Frontend-разработчик",
    specialization: "Фронтенд",
    location: "Удаленно",
    skills: ["React", "TypeScript", "доступность"],
    languages: ["русский", "English"]
  },
  {
    name: "Салтанат Р.",
    headline: "HR-координатор инклюзивного найма",
    specialization: "HR",
    location: "Ош",
    skills: ["найм", "адаптация", "документы"],
    languages: ["кыргызча", "русский"]
  }
];
